# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2887059dba00361a8a65a02fb50e3b9b564450a2cce282ba3ba0b5c164719cbb315f6005076e9f97f3ac8235e4eb1e03531edc3dfe073a2662701b520b3a4e8f

test:
  secret_key_base: 81fe60f8b0ff60705f2e96e1b0cd6ed7e57a4bb8571fa60e107e8c33f800ab3655ca0d4320a8172009baf9dd382d531d3914b46f1abd865c8309edf2989bf6de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
